version: "3.9"

services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
      target: manager
    environment:
      - WORKERS=http://worker1:8081,http://worker2:8081,http://worker3:8081,http://worker4:8081
      - MANAGER_ADDR=:8080
      - MANAGER_MAX_INFLIGHT=256
      - MANAGER_CPU_LIMIT=0
    depends_on:
      - worker1
      - worker2
      - worker3
      - worker4
    ports:
      - "8080:8080"
    restart: unless-stopped

  worker1:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    environment:
      - WORKER_PORT=8081
      - TARGET_BINARY=/opt/target_binary.sh
      - WORKER_MAX_PARALLEL=4
    hostname: worker1
    restart: unless-stopped

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    environment:
      - WORKER_PORT=8081
      - TARGET_BINARY=/opt/target_binary.sh
      - WORKER_MAX_PARALLEL=4
    hostname: worker2
    restart: unless-stopped

  worker3:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    environment:
      - WORKER_PORT=8081
      - TARGET_BINARY=/opt/target_binary.sh
      - WORKER_MAX_PARALLEL=4
    hostname: worker3
    restart: unless-stopped

  worker4:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    environment:
      - WORKER_PORT=8081
      - TARGET_BINARY=/opt/target_binary.sh
      - WORKER_MAX_PARALLEL=4
    hostname: worker4
    restart: unless-stopped
